script/tools/buf/Dockerfile

Here is github.com/bufbuild/buf/releases v0.26.0, I hope it works.

Update github.com/bufbuild/buf/releases from v0.25.0 to v0.26.0

---

script/tools/buf/Dockerfile

Here is github.com/bufbuild/buf/releases v0.27.1, I hope it works.

Update github.com/bufbuild/buf/releases from v0.26.0 to v0.27.1

---

script/tools/buf/Dockerfile

Here is github.com/bufbuild/buf/releases v0.28.0, I hope it works.

Update github.com/bufbuild/buf/releases from v0.27.1 to v0.28.0

---

script/tools/buf/Dockerfile

Here is github.com/bufbuild/buf/releases v0.29.0, I hope it works.

Update github.com/bufbuild/buf/releases from v0.28.0 to v0.29.0

---

script/tools/buf/Dockerfile

Here is github.com/bufbuild/buf/releases v0.30.0, I hope it works.

Update github.com/bufbuild/buf/releases from v0.29.0 to v0.30.0

---

script/tools/buf/Dockerfile

Here is github.com/bufbuild/buf/releases v0.30.1, I hope it works.

Update github.com/bufbuild/buf/releases from v0.30.0 to v0.30.1

---

script/tools/buf/Dockerfile

Here is github.com/bufbuild/buf/releases v0.31.0, I hope it works.

Update github.com/bufbuild/buf/releases from v0.30.1 to v0.31.0

---

script/tools/buf/Dockerfile

Here is github.com/bufbuild/buf/releases v0.31.1, I hope it works.

Update github.com/bufbuild/buf/releases from v0.31.0 to v0.31.1

---

script/tools/buf/Dockerfile

Here is github.com/bufbuild/buf/releases v0.32.0, I hope it works.

Update github.com/bufbuild/buf/releases from v0.31.1 to v0.32.0

---

script/tools/buf/Dockerfile

Here is github.com/bufbuild/buf/releases v0.32.1, I hope it works.

Update github.com/bufbuild/buf/releases from v0.32.0 to v0.32.1

---

script/tools/buf/Dockerfile

Here is github.com/bufbuild/buf/releases v0.33.0, I hope it works.

Update github.com/bufbuild/buf/releases from v0.32.1 to v0.33.0

---

script/tools/buf/Dockerfile

Here is github.com/bufbuild/buf/releases v0.34.0, I hope it works.

Update github.com/bufbuild/buf/releases from v0.33.0 to v0.34.0

---

script/tools/buf/Dockerfile

Here is github.com/bufbuild/buf/releases v0.35.0, I hope it works.

Update github.com/bufbuild/buf/releases from v0.34.0 to v0.35.0

---

script/tools/buf/Dockerfile

Here is github.com/bufbuild/buf/releases v0.35.1, I hope it works.

Update github.com/bufbuild/buf/releases from v0.35.0 to v0.35.1

---

go.mod
go.sum

Here is github.com/stretchr/testify v1.7.0, I hope it works.

Update github.com/stretchr/testify from v1.6.1 to v1.7.0

---

script/tools/buf/Dockerfile

Here is github.com/bufbuild/buf/releases v0.36.0, I hope it works.

Update github.com/bufbuild/buf/releases from v0.35.1 to v0.36.0

---

script/tools/buf/Dockerfile

Here is github.com/bufbuild/buf/releases v0.37.0, I hope it works.

Update github.com/bufbuild/buf/releases from v0.36.0 to v0.37.0

---

script/tools/buf/Dockerfile

Here is github.com/bufbuild/buf/releases v0.37.1, I hope it works.

Update github.com/bufbuild/buf/releases from v0.37.0 to v0.37.1

---

script/tools/buf/Dockerfile

Here is github.com/bufbuild/buf/releases v0.39.1, I hope it works.

Update github.com/bufbuild/buf/releases from v0.38.0 to v0.39.1

---

script/tools/buf/Dockerfile

Here is github.com/bufbuild/buf/releases v0.40.0, I hope it works.

Update github.com/bufbuild/buf/releases from v0.39.1 to v0.40.0

---

Dockerfile
script/tools/buf/Dockerfile

Here is golang 1.16.2, I hope it works.

Update golang from 1.13.8 to 1.16.2

---

script/tools/golangci-lint/Dockerfile

Here is golangci/golangci-lint v1.38.0-alpine, I hope it works.

Update golangci/golangci-lint from v1.31.0-alpine to v1.38.0-alpine

---

Dockerfile
script/tools/buf/Dockerfile

Here is golang 1.16.3, I hope it works.

Update golang from 1.16.2 to 1.16.3

---

script/tools/buf/Dockerfile

Here is github.com/bufbuild/buf/releases v0.41.0, I hope it works.

Update github.com/bufbuild/buf/releases from v0.40.0 to v0.41.0

---

go.mod
go.sum

Here is github.com/json-iterator/go v1.1.11, I hope it works.

Update github.com/json-iterator/go from v1.1.10 to v1.1.11

---

Dockerfile
script/tools/buf/Dockerfile

Here is golang 1.16.4, I hope it works.

Update golang from 1.16.3 to 1.16.4

---

script/tools/golangci-lint/Dockerfile

Here is golangci/golangci-lint v1.40.0-alpine, I hope it works.

Update golangci/golangci-lint from v1.39.0-alpine to v1.40.0-alpine

---

script/tools/buf/Dockerfile

Here is github.com/bufbuild/buf/releases v0.42.1, I hope it works.

Update github.com/bufbuild/buf/releases from v0.41.0 to v0.42.1

---

script/tools/buf/Dockerfile

Here is github.com/bufbuild/buf/releases v0.43.2, I hope it works.

Update github.com/bufbuild/buf/releases from v0.43.1 to v0.43.2

---

Dockerfile
script/tools/buf/Dockerfile

Here is golang 1.16.5, I hope it works.

Update golang from 1.16.4 to 1.16.5

---

go.mod
go.sum

Here is google.golang.org/protobuf v1.27.0, I hope it works.

Update google.golang.org/protobuf from v1.26.0 to v1.27.0

---

go.mod
go.sum

Here is github.com/spf13/viper v1.8.1, I hope it works.

Update github.com/spf13/viper from v1.8.0 to v1.8.1

---

go.mod
go.sum

Here is google.golang.org/protobuf v1.27.1, I hope it works.

Update google.golang.org/protobuf from v1.27.0 to v1.27.1

---

Dockerfile
script/tools/buf/Dockerfile

Here is golang 1.16.6, I hope it works.

Update golang from 1.16.5 to 1.16.6

---

script/tools/buf/Dockerfile

Here is github.com/bufbuild/buf/releases v0.45.0, I hope it works.

Update github.com/bufbuild/buf/releases from v0.44.0 to v0.45.0

---

script/tools/buf/Dockerfile

Here is github.com/bufbuild/buf/releases v0.46.0, I hope it works.

Update github.com/bufbuild/buf/releases from v0.45.0 to v0.46.0

---

script/tools/buf/Dockerfile

Here is github.com/bufbuild/buf/releases v0.48.0, I hope it works.

Update github.com/bufbuild/buf/releases from v0.46.0 to v0.48.0

---

script/tools/buf/Dockerfile

Here is github.com/bufbuild/buf/releases v0.48.2, I hope it works.

Update github.com/bufbuild/buf/releases from v0.48.0 to v0.48.2

---

.dockerignore
Dockerfile
script/tools/buf/Dockerfile

Modify the `script/tools/buf/Dockerfile` helper to verify the `buf` binary with the signatures provided by https://github.com/bufbuild/buf/issues/442
This reinforces `BUF_CHECKSUM`: instead of being a checksum that Renovate ✨somehow✨ identifies, the checksum is verified to be in the signed checksum file released upstream.
Since the key is pinned, pinning `BUF_CHECKSUM` is overkill.

Verify buf
